#page title
page_title                                : Geotag Alpha for Sony - Geotagging that works

# App Info
ios_app_id                                : 6450399211                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : au                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : null
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Geotag Alpha.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Geotag Alpha                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Coming soon! Geotag Alpha makes geotagging for Sony cameras usable. Designed to work in the background, handle reconnections, and energy efficient.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sproutcube                                
your_link                                 : https://sproutcube.com
your_city                                 : Melbourne                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Better geotagging for Sony Alpha cameras
    description                           : Geotag Alpha uses the Bluetooth connection on your Sony camera to push location information to be recorded in your photos' EXIF data. Don't spend time messing with GPX tracks.
    fontawesome_icon_name                 : magic

  - title                                 : Works in the background
    description                           : Geotag Alpha works while in the background, and even handles reconnecting to paired cameras while backgrounded.
    fontawesome_icon_name                 : magic

  - title                                 : Energy Efficient
    description                           : Minimises battery drain by only sending locations to the camera when it changes, and only enables location services when connected.
    fontawesome_icon_name                 : mobile

  - title                                 : Accurate
    description                           : Pushes the latest location on focus. Works on current generation Sony alpha cameras with Bluetooth Remote Control enabled.
    fontawesome_icon_name                 : play-circle

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
